version: "3.9"

services:
  backend:
    image: praveshyadav71/qs_backend_dev:latest
    container_name: qs_backend
    ports:
      - "8001:8001"
    environment:
      - DJANGO_SETTINGS_MODULE=QuickserveBackend.settings
    restart: always

  frontend:
    image: praveshyadav71/frontend-dev:latest
    container_name: qs_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
